name: firebase_mlvision_example
description: Demonstrates how to use the firebase_mlvision plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.5.0
  cupertino_icons: ^0.1.2
  firebase_mlvision:
    path: ../
  firebase_core: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  path: ^1.6.2
  path_provider: ^0.5.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/test_face.jpg
    - assets/test_barcode.jpg
    - assets/test_text.png
    - assets/potholes/dict.txt
    - assets/potholes/manifest.json
    - assets/potholes/model.tflite  
